### ISSUE TITLE
Registers R30 and R31 access

### ISSUE THREAD

**Issue by ryanbinns** [dinuxbg/gnupru#26]
While the current method in `pru/io.h` for accessing R30 and R31 works well, I have had success using
```
register unsigned int __R30 asm ("r30");
register unsigned int __R31 asm ("r31");
```
instead. That way, `__R30` and `__R31` can be used like any other `unsigned int` variable from both C and C++ programs.

**Comment by ryanbinns** [comment]
... until the optimizer steps in and buggers everything up. Never mind.

**Comment by dinuxbg** [comment]
Unfortunately combine and other RTL passes do not treat those registers as truly volatile. And it doesn't look like an issue for mainline: https://gcc.gnu.org/ml/gcc-patches/2015-01/msg02241.html

I might explore adding R30 and R31 as an additional memory space for the GCC PRU port. Volatile memory is correctly handled by RTL.

**Comment by dinuxbg** [comment]
Proposed solution: https://gcc.gnu.org/pipermail/gcc-patches/2021-September/579420.html
