### ISSUE TITLE
Compiler defined compiler macros

### ISSUE THREAD

**Issue by VedantParanjape** [dinuxbg/gnupru#36]
Does pru-gcc have any kind of compiler defined macros, like when i pass -mmcu=am335x.pru0 or am335x.pru1, is there some way i could so something like this:

```
#ifdef __PRU0__
    #define HOSTINT (uint32_t) 1 << 30
#elif __PRU1__
    #define HOSTINT (uint32_t) 1 << 31
#else 
```

**Comment by dinuxbg** [comment]
```
$ pru-gcc -E -dM -mmcu=am335x.pru0 - </dev/null
#define __AM335X_PRU0__ 1
```

The mmcu option actually picks a per-core/SoC file. For the gory details see here: https://github.com/dinuxbg/gnuprumcu/blob/master/device-specs/am335x.pru0

**Comment by VedantParanjape** [comment]
Thanks this helped !
