### ISSUE TITLE
Implementation of PRU LMBD (Left-most bit detect) OPCODE

### ISSUE THREAD

**Issue by olsonse** [dinuxbg/gnupru#40]
The documentation states that all the standard PRU core V3 opcodes (as implemented by the pasm assembler) were being implemented.  Is there a strong reason why LMBD was not implemented?  From the pasm source code, it appears to be clear that the LMBD instruction began to be implemented in the PRU core v1 and is still implemented in V3.  I hand-coded the instruction into the PRU instruction memory to test whether this still works on the AM3358 of the Beaglebone Black, and *yes*, it is supported just fine on this PRU core.

Doing some preliminary changes (basedlined from the master branch at sourceware.org/git/binutils-gdb.git), it looks pretty simple to implement the LMBD instruction.  Here is is the diff of my attempt:

[gas-pru-lmbd-intruction.patch.gz](https://github.com/dinuxbg/gnupru/files/5442341/gas-pru-lmbd-intruction.patch.gz)

Or see patch from forked repository: olsonse/binutils-gdb@128fd3efdf0903a93bfd8e722ee80c9fc4886689

**Comment by olsonse** [comment]
Patch was tested on Beaglebone Black (compiled for arm host with --target=pru).  Generated code works just find and "objdump -D" disassembly works fine also.

**Comment by dinuxbg** [comment]
There is no reason to leave LMBD. I either unintentionally missed it, or got it confused with SCAN which is not supported by V3 cores.

 PRU binutils is maintained in mainline. Can you please send your patch to binutils@sourceware.org ? You might need to sign copyright papers if change is deemed non-trivial by GNU folks. 

Can you please add a testcase with register  operand, e.g.:
```
  lmbd	r0, r1, r2.b2
```

**Comment by olsonse** [comment]
I've amended my patch.  It is interesting (though not surprising) that your suggested instruction gets decompiled back as

    lmbd r0, r1, sp.b2

I'll leave it that way unless you have any objections.

**Comment by olsonse** [comment]
As you will see, I sent in a patch to the mailing list (you were CC'd).

**Comment by dinuxbg** [comment]
Binutils patch has been merged, thanks. I'll send updates for GCC and Simulator.
