### ISSUE TITLE
Device spec file not found

### ISSUE THREAD

**Issue by VedantParanjape** [dinuxbg/gnupru#41]
Cross posting here for relevance:

https://github.com/VedantParanjape/simpPRU/issues/25

Building simppru fails on gcc pru 12. Due to device spec file not found error.

**Comment by VedantParanjape** [comment]
@dinuxbg gnuprumcu is installed in the given system, still it fails to run.

**Comment by dinuxbg** [comment]
I managed to build simppru using https://github.com/rcn-ee/repos/pull/55 . Closing.

FYI, the `sbuild` tool creates a separate chroot for building the given package. This is a safeguard, and decouples the build process from the host. Also, `sbuild` installs only the declared dependencies. That way you can catch if you have missed some dependency.
