### ISSUE TITLE
Missed optimization: Backend fails to zero-extend using instruction operands

### ISSUE THREAD

**Issue by dinuxbg** [dinuxbg/gnupru#9]
The following C snippet:
```C
  unsigned int x = (unsigned int)a + (unsigned char)b;
```
Will compile to the inefficient (but still correct):
```asm
   mov r15, r15.b0
   add r16, r14, r15
```
Instead of the more-optimal:
```asm
   add r16, r14, r15.b0
```

**Comment by OctalS** [comment]
How much cpu cycles are in the first and second case ?

**Comment by dinuxbg** [comment]
Two an one cycle, respectively.

All PRU instructions take one cycle to execute, except the load/store instructions.

**Comment by dinuxbg** [comment]
Looks like AArch64 is having the same issue: http://www.slideshare.net/linaroorg/hkg15405-redundant-zerosignextension-elimination-in-gcc . On to reading the aarch64 machine description...
